# Generated by Django 3.2.7 on 2021-09-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='First_name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last_name')),
            ],
        ),
    ]
